FROM ubuntu:focal
WORKDIR /opt/ErpNet.FP

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
        \
        # .NET dependencies
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu66 \
        libssl1.1 \
        libstdc++6 \
        zlib1g \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 8.0 -Runtime dotnet -InstallDir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /usr/src/ErpNet.FP

RUN cd /usr/src \
    && git clone https://github.com/erpnet/ErpNet.FP.git \
    && cd ErpNet.FP \
COPY ../ouput.xml /usr/src/ErpNet.FP/ouput.xml
RUN dotnet msbuild output.xml
